services:
  config:
    build: .
    ports: 
     - "5001:5000"
    environment:
     - "DATA_ENDPOINT"
  training-data:
    build: .
    ports:
      - "5002:5000"
  trainer:
    build: .
    ports:
     - "5003:5000"